services:
  
  nginx:
    image: nginx:alpine
    container_name: quiz-nginx
    ports:
      - "9310:80"
    volumes:
      - ./:/var/www
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.4-fpm
    container_name: quiz-php
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:latest
    container_name: quiz_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: 1234
    volumes:
      - type: bind
        source: ./mysql/data
        target: /var/lib/mysql
    ports:
      - "3366:3306"