server {
    listen 80;
    server_name localhost;
    # docker exec -it quiz-nginx sh
    # ls var/www/ --- public/ contains index.php
    root /var/www/public;
    index index.php;
    charset utf-8;

    location / {
        # try for file, path, if neither: pass to index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    # If URL ends on a .php:
    location ~ \.php$ {
        # load HTTP-HEADER
        include fastcgi_params;

        # pass Request to quiz-php:9000 (docker-container:TCP-Port)
        fastcgi_pass quiz-php:9000;

        # which php file is to be executed, e.g. /var/www/public + /index.php
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # no need to pass additional path_info, since Router uses $_SERVER['REQUEST_URI']
    }

    # block ALL hidden files
    location ~ /\. {
        deny all;
    }
}