server {
    listen 80;
    server_name localhost;
    # docker exec -it quiz-nginx sh
    # ls var/www/ --- public/ contains index.php
    root /var/www/public; 
    index index.php;

    location / {
        # try for file, path, if neither pass to index.php
        try_files $uri $uri/ /index.php?query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass quiz-php:9000; # Name of php docker container
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\. {
        deny all;
    }
}