@startuml
left to right direction

actor "Player" as P
actor "Admin" as A

rectangle "Quiz App" {

  package "Authentifizierung" {
    usecase "Registrieren" as UC1
    usecase "Anmelden" as UC2
    usecase "Abmelden" as UC3
  }

  package "Quiz" {
    usecase "Quiz konfigurieren" as UC4
    usecase "Kategorie wählen" as UC5
    usecase "Quiz spielen" as UC6
    usecase "Ergebnis ansehen" as UC7
  }

  package "Übersichten" {
    usecase "Startseite / Statistiken ansehen" as UC8
    usecase "Rangliste ansehen" as UC9
  }

  package "Adminbereich" {
    usecase "Fragen verwalten" as UC10
    usecase "Kategorien verwalten" as UC11
    usecase "Nutzer einsehen" as UC12
  }
}

UC4 ..> UC5 : <<include>>
UC4 ..> UC6 : <<include>>
UC6 ..> UC7 : <<include>>

P -- UC1
P -- UC2
P -- UC3
P -- UC4
P -- UC8
P -- UC9

A --|> P
A -- UC10
A -- UC11
A -- UC12

@enduml